import { CSSProperties } from 'react';

const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const, // Use 'as const' for literal types
    height: '100vh',
    backgroundColor: '#f9fafb',
  },
  header: {
    display: 'flex',
    flexDirection: 'row' as const,
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 22px',
    backgroundColor: '#007bff',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 800,
    letterSpacing: 1.1,
  },
  logoutBtn: {
    display: 'flex',
    flexDirection: 'row' as const,
    alignItems: 'center',
    backgroundColor: '#0056b3',
    padding: '10px 18px',
    borderRadius: 28,
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.12)',
    color: '#fff',
    fontWeight: 700,
    fontSize: 15,
    border: 'none',
    cursor: 'pointer',
  },
  searchSection: {
    padding: 20,
    backgroundColor: '#fff',
    borderBottom: '1px solid #e1e4e8',
  },
  label: {
    fontSize: 15,
    marginBottom: 8,
    color: '#444',
    fontWeight: 600,
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'row' as const,
    alignItems: 'center',
  },
  input: {
    flex: 1,
    height: 44,
    border: '1px solid #ccc',
    borderRadius: 12,
    padding: '0 14px',
    backgroundColor: '#fff',
    fontSize: 16,
    color: '#222',
  },
  button: {
    backgroundColor: '#007bff',
    padding: '12px 18px',
    borderRadius: 12,
    marginLeft: 12,
    boxShadow: '0 3px 5px rgba(0, 86, 179, 0.3)',
    color: '#fff',
    fontWeight: 700,
    fontSize: 16,
    border: 'none',
    cursor: 'pointer',
  },
  error: {
    color: '#e55353',
    padding: '0 20px',
    marginTop: 8,
  },
  warning: {
    color: '#f0a500',
    padding: '0 20px',
    marginTop: 8,
  },
  mapSection: {
    flex: 1,
    minHeight: 260,
    borderTop: '1px solid #e1e4e8',
    margin: '12px 16px',
    borderRadius: 14,
    overflow: 'hidden',
    boxShadow: '0 5px 8px rgba(0, 0, 0, 0.1)',
  },
  listContainer: {
    padding: 24,
    backgroundColor: '#f9fafb',
    overflowY: 'auto' as const,
    flex: 1,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 800,
    marginBottom: 18,
    color: '#222',
  },
  noShops: {
    fontSize: 16,
    color: '#888',
    fontStyle: 'italic' as const,
  },
  shopCard: {
    backgroundColor: '#fff',
    padding: '20px',
    borderRadius: 16,
    marginBottom: 20,
    boxShadow: '0 5px 10px rgba(0, 0, 0, 0.06)',
    cursor: 'pointer',
  },
  statusIndicator: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginRight: 12,
  },
  shopCardHeader: {
    display: 'flex',
    flexDirection: 'row' as const,
    alignItems: 'center',
    marginBottom: 12,
  },
  shopName: {
    fontSize: 20,
    fontWeight: 800,
    color: '#111',
  },
  shopLocation: {
    fontSize: 15,
    color: '#555',
    marginBottom: 12,
  },
  distanceRow: {
    display: 'flex',
    flexDirection: 'row' as const,
    justifyContent: 'space-between',
    borderTop: '1px solid #eee',
    paddingTop: 14,
  },
  distanceText: {
    fontSize: 15,
    color: '#444',
  },
} satisfies Record<string, CSSProperties>;

export default styles;