export enum PositionType {
    TOP_CENTER = "TOP_CENTER",
    TOP_LEFT = "TOP_LEFT",
    TOP_RIGHT = "TOP_RIGHT",
    MIDDLE_CENTER = "MIDDLE_CENTER",
    MIDDLE_LEFT = "MIDDLE_LEFT",
    MIDDLE_RIGHT = "MIDDLE_RIGHT",
    BOTTOM_LEFT = "BOTTOM_LEFT",
    BOTTOM_RIGHT = "BOTTOM_RIGHT",
    BOTTOM_CENTER = "BOTTOM_CENTER"

}

