---
- hosts: rxhms-ecom-web
  become: True
  tasks:
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present
  
  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Start and enable Docker service
    service:
      name: docker
      state: started
      enabled: yes
  - name: Install python3-docker (official package)
    apt:
      name: python3-docker
      state: present
  
  - name: Log in to the private repository
    docker_login:
      username: chsdev
      password: dckr_pat_KqE9IQnCkW6e3uj2S7_l5Zb1ow4
      registry_url: docker.io/chsdev/rxhms-ecom-web
    tags:
      - docker

  - name: Stop running containers
    docker_container:
      name: "rxhms-ecom-web"
      state: stopped
    failed_when: false
  
  - name: Remove old container
    docker_container:
      name: "rxhms-ecom-web"
      state: absent
    tags:
      - docker

  - name: Remove old images
    docker_image:
      name: "chsdev/rxhms-ecom-web:version-1.0.1"
      state: absent

  - name: Pull the container image from the private repository
    docker_image:
      name: "chsdev/rxhms-ecom-web:version-1.0.1"
      source: pull
    tags:
      - docker
  
  - name: run the container
    docker_container:
      name: rxhms-ecom-web
      image: "chsdev/rxhms-ecom-web:version-1.0.1"
      state: started
      published_ports:
        - "3000:3000"
    tags:
      - docker